name: Node version chaging

on: push

jobs:
  runs-on: ubuntu-latest
  steps: 
    - name: node version
      run: node -v
    - name: changing node version
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: printing the node version
      run: node -v 