name: Docker-container

on: push

jobs:
  node-docker:
    runs-on: ubuntu:latest
    container: 
      image: node:16-alpine
    steps:
      - name: Log node version
        run: | 
          node -v 
          npm -v 
          cat /etc/os-release
          
