name: Custom Event in Github to trigger GitHub WOrkflow/Actions
on:   
  repository_dispatch:    
    types: 
      - dev
      - stage
      - production

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest  
    steps:
      - name: Using run you can the bash shell                 
        run: echo "Hello this is our first github action"     
      - name: multline script    
        run: |
          node -v
          npm -v 
            - name: python command
      - name: python shell 
        run: |
          import platform
          print
          (platform.processor())
        shell: python      
      - name: Failing step
        id: demo
        run: exit 1
  run-windows-commands:
    runs-on: windows-latest
    if: ${{ failure() }}
    needs: ["run-shell-command"]    
    steps:
      - name: Powershell Directory
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash