name: Github Encryption & Decryption
on:   
  push:
    branches: [ master ]
env:
  TOKEN: Github

jobs:
  github_checkout_stage:
    runs-on: ubuntu-latest
    steps:
    - name:  checkout Code
      uses: actions/checkout@v1
    - name: Decrypt File
      run: gpg --quiet --batch  --yes --decrypt --passphrase="$PASS"  --output $HOME/secret.json secret.gpg
      env: 
        PASS:  ${{ secrets.GPG_PASS }}
    - name: Print the file context
      run: cat $HOME/secret.json

