name: My first github workflow
on:    #Type of Event that will trigger the github worflow
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
jobs:
  run-shell-command: 
    runs-on: ubuntu-latest  #With this you can use type of runner with specific version like ubuntu/Windows/Macos
    steps:
      - name: Using run you can the bash shell                 #Name of the step inside steps
        run: echo "Hello this is our first github action"      #To run the shell command use run 
      - name: multline script     #USing pipe symbol you can run multiple command 
        run: |
          node -v
          npm -v 
