name: My first github workflow
on:    #Type of Event that will trigger the github worflow
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
jobs:
  run-shell-command: 
    runs-on: ubuntu-latest  #With this you can use type of runner with specific version like ubuntu/Windows/Macos
    steps:
      - name: Using run you can the bash shell                 #Name of the step inside steps
        run: echo "Hello this is our first github action"      #To run the shell command use run 
      - name: multline script     #USing pipe symbol you can run multiple command 
        run: |
          node -v
          npm -v 
            - name: python command
      - name: python shell  #This is to run the in python shell
        run: |
          import platform
          print
          (platform.processor())
        shell: python      
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]    #This is basically a type of dependency that this stepd should run only if previous stage is successful
    steps:
      - name: Powershell Directory
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash