name: Build & push Docker image to ECR
on:
  push:
    branches:
      - "master"
env:
  AWS_REGION:   us-west-2                         
  ECR_REPOSITORY_NAME: github-test-action         
  CONTAINER_NAME: github-action 
  BRANCH_NAME: main
  GITHUB_REPO: "SOHAN-cyber/NODE-MERN-PROJECT"                
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ GITHUB_REPO }}
        token: ${{ secrets.TOKEN }}
        ref: ${{ BRANCH_NAME }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Installing dependency
      uses: actions/setup-node@v3
      with:
        node_version: 14
    - name: Installing dependency
      run: |
        ls -a
        npm i
    - name: Creating a ECR
      run: aws ecr create-repository --repository-name $ECR_REPOSITORY_NAME --region $AWS_REGION
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
        TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push  $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"
